<?php
/**
 * @file
 *  Constants for the "Sample" installation profile.
 *
 *  © 2015 Red Bottle Design, LLC. All rights reserved.
 *
 * @author  Guy Paddock (guy.paddock@redbottledesign.com)
 */

/**
 * Machine name for the installation profile.
 *
 * @var string
 */
define('SA_PROFILE_NAME', 'sample');

/**
 * The human-friendly name of this profile.
 *
 * @var string
 */
define('SA_PROFILE_FRIENDLY_NAME', 'Sample Installation');