<?php
/**
 * @file
 *   Core code for the "Sample Development UI" feature.
 *
 *   Copyright (C) 2015-2017  Red Bottle Design, LLC
 *
 *   This program is free software: you can redistribute it and/or modify it
 *   under the terms of the GNU General Public License as published by the Free
 *   Software Foundation, either version 3 of the License, or (at your option)
 *   any later version.
 *
 *   This program is distributed in the hope that it will be useful, but WITHOUT
 *   ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *   FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 *   more details.
 *
 *   You should have received a copy of the GNU General Public License along
 *   with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @author Guy Paddock (guy@redbottledesign.com)
 */

require_once('sample_devel.features.inc');
require_once('sample_devel.constants.inc');

/**
 * Implements hook_module_implements_alter().
 */
function sample_devel_module_implements_alter(&$implementations, $hook) {
  // Move this module last to prevent clashing with HaW Soft Delete
  if ($hook == 'site_post_install') {
    $group = $implementations[SADE_MODULE_NAME];
    unset($implementations[SADE_MODULE_NAME]);
    $implementations[SADE_MODULE_NAME] = $group;
  }
}
