#!/bin/bash
# /etc/init.d/teamcity
# Carry out specific functions when asked to by the system
TEAMCITY_HOME=/opt/teamcity
TEAMCITY_USER=teamcity


AUTHBIND=""

# Check for Authbind, and use it if available so we can bind to port 80
if command -v authbind >/dev/null 2>&1; then
  AUTHBIND="authbind --deep"
fi

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root." 1>&2;
   exit 1;
fi

case "$1" in
  start)
    echo "Starting TeamCity server.";
    sudo -u $TEAMCITY_USER $AUTHBIND $TEAMCITY_HOME/bin/teamcity-server.sh start;
    ;;
  stop)
    echo "Stopping TeamCity server.";
    sudo -u $TEAMCITY_USER $AUTHBIND $TEAMCITY_HOME/bin/teamcity-server.sh stop;
    ;;
  restart)
    $0 stop;
    echo;

    sleep 5;
    $0 start;
    ;;
  *)
    echo "Usage:" $0 "{start|stop|restart}";
    exit 1;
    ;;
esac;

exit 0;
