#!/bin/bash
# /etc/init.d/teamcity
# Carry out specific functions when asked to by the system
TEAMCITY_HOME=/opt/teamcity/BuildAgent
TEAMCITY_USER=teamcity

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root." 1>&2;
   exit 1;
fi

case "$1" in
  start)
    echo "Starting TeamCity build agent.";
    sudo -u $TEAMCITY_USER $TEAMCITY_HOME/bin/agent.sh start;
    ;;
  stop)
    echo "Stopping TeamCity build agent.";
    sudo -u $TEAMCITY_USER $TEAMCITY_HOME/bin/agent.sh stop;
    ;;
  restart)
    $0 stop;
    echo;

    sleep 5;
    $0 start;
    ;;
  *)
    echo "Usage:" $0 "{start|stop|restart}";
    exit 1;
    ;;
esac;

exit 0;
